compiler_command = "python3 tools/asm_processor/build.py tools/ido7.1/cc -- mips-linux-gnu-as -G 0 -I include -I ultralib/include -I ultralib/include/ido -I ultralib/include/PR -I ultralib/src -EB -mtune=vr4300 -march=vr4300 -- -G 0 -O2 -non_shared -fullwarn -verbose -Xcpluscomm -nostdinc -Wab,-r4300_mul $flags -mips2 -I include -I ultralib/include -I ultralib/include/ido -I ultralib/include/PR -I ultralib/src -DF3DEX_GBI_2 -D_LANGUAGE_C -DNDEBUG -D_FINALROM -DBUILD_VERSION=VERSION_I -c"
assembler_command = "mips-linux-gnu-as -G0 -I include -I ultralib/include -I ultralib/include/ido -I ultralib/include/PR -I ultralib/src -EB -mtune=vr4300 -march=vr4300"
compiler_type = "ido"

[preserve_macros]
"g[DS]P.*" = "void"
"gs[DS]P.*" = "void"
"G_IM_SIZ_.*" = "int"
"G_[AC]C.*" = "int"
ABS = "int"
ABS_ALT = "int"
SQ = "int"
ARRAY_COUNT = "int"
ARRAY_COUNTU = "int"
CLAMP = "int"
NULL = "int"

[decompme.compilers]
"tools/ido7.1/cc" = "ido7.1"
"tools/ido5.3/cc" = "ido5.3"
